swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact:
    email: fdelosriosfernandez@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8090'
basePath: /
tags:
  - name: itineraries-controller
    description: Itineraries Controller
paths:
  '/itineraries/v1/{source}':
    get:
      tags:
        - itineraries-controller
      summary: Obtain itineraries (faster and most direct) from a city to another
      operationId: getItinerariesUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: source
          in: path
          description: source
          required: true
          type: string
        - name: destination
          in: query
          description: destination
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Itineraries'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
definitions:
  Itineraries:
    type: object
    properties:
      citySource:
        type: string
      destination:
        type: string
      direct:
        $ref: '#/definitions/Itinerary'
      faster:
        $ref: '#/definitions/Itinerary'
  Itinerary:
    type: object
    properties:
      connections:
        type: integer
        format: int32
      route:
        type: array
        items:
          type: string
      time:
        type: integer
        format: int32

