spring:
  data:
    mongodb:
      host: mongo
      database: connections

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

server:
  port: 8080

logging:
  file: /var/log/project.log
